### PR TITLE
Fix GPX export, omitting unkown types, refactoring

### LINKED ISSUE #18: Getting empty output on GEOJSON -> GPX
I am getting an "empty" (no features in it) GPX output on the attached file.

[654.geojson.txt](https://github.com/Yermo/geoPHPwithFeatures/files/1934811/654.geojson.txt)

    php geo_convert.php --input-path=../../654.geojson --input-format=geojson --output-path=../../654.gpx --output-format=gpx

### PR DESCRIPTION
**Pull request by amenk**
(needs PHP7)

Closes #18

### CODE REVIEW

**Comment by amenk** [comment]
here you go, I hope you do not mind about supporting only php7

**Comment by Yermo** [comment]
Unfortunately, I'm stuck running hhvm for the foreseeable future so requiring PHP7 is not going to work for me. I will eventually make the switch but it's probably going to be much later this year. 

Any chance you can make it PHP 5.6 compatible?

**Comment by amenk** [comment]
Sure, I realized anyways that the project I want to use this, is still running PHP5.5 :grinning:

**Comment by Yermo** [comment]
It's interesting that the tests pass with hhvm but fail with PHP7 with a redeclaration of getPrecedence() error. 

```
PHP Fatal error:  Cannot redeclare getPrecedence() (previously declared in /usr/local/YML/WWW/miles-by-motorcycle.com/html/formvista/fvtk/src/3rdparty/geoPHPwithFeatures/lib/adapters/GPX.class.php:1072) in /usr/local/YML/WWW/miles-by-motorcycle.com/html/formvista/fvtk/src/3rdparty/geoPHPwithFeatures/lib/adapters/GPX.class.php on line 1072
yml@cylon:/usr/local/WWW/miles-by-motorcycle.com/html/formvista/fvtk/src/3rdparty/geoPHPwithFeatures/tests$ gvim ../lib/adapters/GPX.class.php 
```

While I don't want to require PHP7 support, where possible I'd like it to run with both.

**Comment by Yermo** [comment]
Thanks for fix.

**Pull request merged**
